inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'examples/*'
    - 'geoengineer.gemspec'
    - 'lib/geoengineer/templates/*'

Style/StringLiterals:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

# Given that GeoEngineer is a DSL which encourages similarity to multiline blocks this is disabled
Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

# Increase these a bit
Metrics/LineLength:
  Max: 130 # from 80

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20 # from 10
  # Rubocop auto-gen was not correctly identifying this.
  Exclude:
    - 'lib/geoengineer/resources/aws/ses/aws_ses_event_destination.rb'
    - 'lib/geoengineer/resources/aws/vpc/aws_security_group.rb'

# Offense count: 2
Metrics/AbcSize:
  Max: 20
  # Rubocop auto-gen was not correctly identifying this.
  Exclude:
    - 'lib/geoengineer/resources/aws/ses/aws_ses_event_destination.rb'
    - 'lib/geoengineer/resources/aws/api_gateway/helpers.rb'
    - 'lib/geoengineer/resources/aws/vpc/aws_security_group.rb'

Style/Lambda:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/RedundantSelf:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 300

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 300

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
